package SemesterProject.Demand;

import SemesterProject.Part;

public class DemandItem {
    private Part part;
    private int quantityNeeded;
    private boolean isAutoGenerated;

    public DemandItem(Part part, int quantityNeeded, boolean isAutoGenerated) {
        this.part = part;
        this.quantityNeeded = quantityNeeded;
        this.isAutoGenerated = isAutoGenerated;
    }

    public Part getPart() {return part;}
    public int getQuantityNeeded() {return quantityNeeded;}
    public double getTotalCost() {return part.getUnitPrice() * quantityNeeded;}
}