
package SemesterProject.Demand;
import SemesterProject.Part;

public class DemandItem {
    private Part part;
    private int requiredQuantity;
    private boolean autoGenerated; // true = automatic, false = manual

    public DemandItem(Part part, int requiredQuantity, boolean autoGenerated) {
        this.part = part;
        this.requiredQuantity = requiredQuantity;
        this.autoGenerated = autoGenerated;
    }

    public Part getPart() {
        return part;
    }

    public int getRequiredQuantity() {
        return requiredQuantity;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public double getTotalCost() {
        return requiredQuantity * part.getUnitPrice();
    }

    @Override
    public String toString() {
        return part.getName() +
                " | Qty: " + requiredQuantity +
                " | Cost: " + getTotalCost() +
                " | " + (autoGenerated ? "AUTO" : "MANUAL");
    }
}
