package SemesterProject.Demand;

import SemesterProject.Part;

public class DemandItem {
    private Part part;
    private int quantityNeeded;
    private boolean isAutoGenerated;

    public DemandItem(Part part, int quantityNeeded, boolean isAutoGenerated) {
        this.part = part;
        this.quantityNeeded = quantityNeeded;
        this.isAutoGenerated = isAutoGenerated;
    }

    public Part getPart() {
        return part;
    }

    public int getQuantityNeeded() {
        return quantityNeeded;
    }

    /*public boolean isAutoGenerated() {
        return isAutoGenerated;
    }*/

   // Helper methods for TableView binding
   /* public String getPartName() { return part.getName(); }
    public String getCarModel() { return part.getCarModel(); }
*/
    // NEW: Method to calculate total cost for the view
    public double getTotalCost() {
        return part.getUnitPrice() * quantityNeeded;
    }
}