package SemesterProject.GUI;

import SemesterProject.Body.*;
import SemesterProject.Exception.UserCreationException;
import SemesterProject.InventoryManagment.InventoryManager;
import SemesterProject.Login.Admin;
import SemesterProject.Login.LoginManager;
import SemesterProject.DatabaseManager;
import SemesterProject.Part;
import SemesterProject.Sales.Sale;
import SemesterProject.User;
import SemesterProject.Supplier.LocalSupplier;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.stage.Stage;
import SemesterProject.Demand.DemandManager;
import SemesterProject.Login.PasswordResetRequest;
import SemesterProject.Exception.UserAlreadyExistsException;
import SemesterProject.Exception.UserNotFoundException;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class MainApp extends Application {

    private Stage primaryStage;
    private User currentUser;

    // Managers
    private InventoryManager inventoryManager;
    private DemandManager demandManager;
    private DashboardManager dashboardManager;
    private LoginManager loginManager;
    private DatabaseManager dbManager;

    // Lists
    private List<Part> masterPartList = new ArrayList<>();
    private List<Sale> masterSaleList = new ArrayList<>();
    private final LocalSupplier mockSupplier = new LocalSupplier("MockSupplier", "N/A", "N/A", "N/A", "N/A");

    @Override
    public void start(Stage primaryStage) throws UserCreationException {
        this.primaryStage = primaryStage;
        initializeData();
        showLoginScreen();
    }

    private void initializeData() throws UserCreationException {
        // 1. Initialize In-Memory DB (and other managers)
        dbManager = new DatabaseManager();
        loginManager = new LoginManager(dbManager);
        inventoryManager = new InventoryManager(dbManager);
        demandManager = new DemandManager();

        loadAndPopulateData();

        dashboardManager = new DashboardManager(masterPartList, masterSaleList, demandManager);
    }

    private void loadAndPopulateData() {
        // Load parts from DB
        masterPartList.clear();
        masterPartList.addAll(dbManager.getAllParts());

        // If DB is empty, load mock data
        if (masterPartList.isEmpty()) {
            try {
                loadMockInventoryAndSaveToDB();
                masterPartList.clear();
                masterPartList.addAll(dbManager.getAllParts());
            } catch (Exception e) {
                System.err.println("Error loading mock data: " + e.getMessage());
            }
        }

        // Load sales
        masterSaleList.clear();
        masterSaleList.addAll(dbManager.getAllSales());

        // Sync Inventory Manager
        inventoryManager.getInventory().clear();
        inventoryManager.getInventory().addAll(masterPartList);

        // Initial Demand Check
        demandManager.generateAutoDemands(masterPartList);
    }

    private int getRandomStock() {
        return new Random().nextInt(46) + 5;
    }

    private void loadMockInventoryAndSaveToDB() throws Exception {
        String t = null; // ID auto-generated by DBManager
        dbManager.addPart(new FrontLaminatedGlass(t, "Corolla 2000 FLG", "Corolla 2002", getRandomStock(), 5, 18000, mockSupplier));
        dbManager.addPart(new FrontGlass(t, "Civic X FG", "Civic X", getRandomStock(), 5, 9500, mockSupplier));
        dbManager.addPart(new RearGlass(t, "Corolla 2022 RG", "Corolla 2022", getRandomStock(), 5, 22000, mockSupplier));
        dbManager.addPart(new DoorGlass(t, "Civic X DG", "Civic X", getRandomStock(), 5, 7500, mockSupplier));
        dbManager.addPart(new FrontBumper(t, "Corolla Bumper", "Corolla 2022", getRandomStock(), 5, 35000, mockSupplier));
        dbManager.addPart(new FrontLaminatedGlass(t, "Civic X FLG", "Civic X", getRandomStock(), 5, 25000, mockSupplier));
        dbManager.addPart(new FrontGlass(t, "Civic X FG Low Stock", "Civic X", getRandomStock(), 5, 12000, mockSupplier));
    }

    public void showLoginScreen() {
        LoginView loginView = new LoginView(this);
        Scene scene = new Scene(loginView, 400, 300);
        primaryStage.setTitle("IMS Login");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public void showMainDashboard(User user) {
        this.currentUser = user;
        MainLayout mainLayout = new MainLayout(this, user, inventoryManager, demandManager, dashboardManager, masterPartList);
        Scene scene = new Scene(mainLayout, 1100, 750);
        primaryStage.setTitle("Auto Parts IMS - Logged in as: " + user.getUsername());
        primaryStage.setScene(scene);
        primaryStage.centerOnScreen();
    }

    public boolean authenticate(String username, String password) {
        User authenticatedUser = loginManager.login(username, password);
        if (authenticatedUser != null) {
            showMainDashboard(authenticatedUser);
            return true;
        }
        return false;
    }

    public void addUserPart(Part newPart) throws Exception {
        dbManager.addPart(newPart);
        masterPartList.add(newPart);
        inventoryManager.getInventory().add(newPart);
        demandManager.generateAutoDemands(masterPartList);
        dashboardManager.updateDashboardData();
    }

    // =================================================================
    // ACTIONS (Used by Tile GUI)
    // =================================================================

    public void increaseStock(Part part) {
        try {
            int newStock = part.getCurrentStock() + 1;
            part.setCurrentStock(newStock);
            inventoryManager.updateStock(part, 1);

            // Re-check demands (item might have moved out of low stock)
            demandManager.generateAutoDemands(masterPartList);
            dashboardManager.updateDashboardData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void recordSale(Part part) {
        try {
            int newStock = part.getCurrentStock() - 1;
            if (newStock < 0) return; // Prevent negative stock

            // 1. Log Sale
            String userId = currentUser != null ? currentUser.getUserId() : "U00";
            Sale newSale = new Sale(part.getName(), 1, part.getUnitPrice());
            dbManager.addSale(newSale, part.getPartId(), userId);
            masterSaleList.add(newSale);

            // 2. Decrease Stock
            part.setCurrentStock(newStock);
            inventoryManager.updateStock(part, -1);

            // 3. AUTO-DEMAND LOGIC
            // This function checks ALL parts. If this specific part dropped
            // to 5 or below, it will be automatically added to the demand list.
            demandManager.generateAutoDemands(masterPartList);

            // 4. Update Dashboard
            dashboardManager.updateDashboardData();

            // Optional: Print to console for debugging
            if (newStock <= 5) {
                System.out.println("Part [" + part.getName() + "] is low stock (" + newStock + "). Added to Demand List.");
            }

        } catch (Exception e) {
            System.err.println("Error recording sale: " + e.getMessage());
        }
    }

    // =================================================================
    // Getters & Delegation
    // =================================================================

    public List<Part> getMasterPartList() { return masterPartList; }
    public List<Sale> getMasterSaleList() { return masterSaleList; }
    public List<User> getActiveUsersList() { return loginManager.getActiveUsers(); }
    public LocalSupplier getMockSupplier() { return mockSupplier; }

    public String requestPasswordReset(String username) {
        User u = findUser(username);
        if (u == null) return "User not found.";
        if (u.getRole() != SemesterProject.Login.UserRoles.STAFF) return "Only Staff can reset.";
        loginManager.requestPasswordReset(username);
        return "Request sent.";
    }

    public List<PasswordResetRequest> getPendingPasswordResetRequests() {
        return loginManager.getPendingRequests();
    }

    public User findUser(String username) {
        return loginManager.findUser(username);
    }

    public boolean adminApprovePasswordReset(String staff, String pass) {
        if (currentUser instanceof Admin) {
            return loginManager.approvePasswordReset(currentUser.getUsername(), staff, pass);
        }
        return false;
    }

    public boolean removeUser(String username) throws UserNotFoundException {
        return dbManager.removeUser(username);
    }

    public boolean updateUserDetails(String old, String newU, String newN) throws UserAlreadyExistsException {
        return dbManager.updateUserDetails(old, newU, newN);
    }

    private void showAlert(String title, String content, Alert.AlertType type) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setContentText(content);
        alert.showAndWait();
    }

    public static void main(String[] args) {
        launch(args);
    }

    public void addUser(User newUser) {
        // Implementation if needed
    }
}